declare const process: {
  env: {
    EXPO_PUBLIC_GOOGLE_ANDROID_DEV_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_ANDROID_PROD_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_DEV_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_PROD_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
  };
};
